RAID = [
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧 𝗦𝗕𝗦𝗘𝗘𝗘𝗘𝗘 𝗦𝗘𝗘𝗫𝗫𝗫𝗬𝗬𝗬𝗬𝗬 😘💋",
    "𝗧𝗘𝗜𝗥𝗥𝗥𝗥 𝗠𝗔𝗔𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔𝗔𝗔 𝗥𝗔𝗣𝗘𝗘𝗘𝗘𝗘𝗘 𝗞𝗥𝗞𝗘𝗘𝗘𝗘 𝗕𝗛𝗔𝗚𝗚𝗚𝗚𝗚𝗚 𝗝𝗔𝗔𝗔𝗔𝗨𝗡𝗚𝗔𝗔𝗔 👅🤣🤣",
    "𝗧𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔𝗔 𝗣𝗢𝗥𝗡 𝗛𝗨𝗕 𝗠𝗔𝗜𝗜 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗙𝗔𝗔𝗗𝗡𝗘 𝗔𝗔𝗚𝗬𝗘 𝗛𝗔𝗜 𝗕𝗘𝗧𝗜𝗖𝗛𝗢𝗗⚡️⚡️⚡️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗖𝗛𝗨𝗧 𝗙𝗔𝗧𝗘𝗚𝗜 𝗞𝗜𝗨𝗞𝗜 𝗦𝗕𝗦𝗘 𝗙𝗔𝗦𝗧𝗘𝗦𝗧 𝗕𝗢𝗧 𝗔𝗔𝗚𝗔𝗬𝗔 𝗛𝗔𝗜 𝗧𝗚 𝗣𝗘😈😈⚡️",
    "𝗧𝗥𝗜𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗟𝗘𝗞𝗥 𝗕𝗛𝗔𝗚 𝗝𝗔𝗔𝗨𝗡𝗚𝗔 🤣💋𝗔𝗨𝗥 𝗫𝗫𝗫 𝗕𝗔𝗡𝗔𝗨𝗡𝗚𝗔 🤤",
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗫𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗫𝗛𝗢𝗗𝗧𝗘 𝗫𝗛𝗢𝗗𝗧𝗘 𝗕𝗔𝗫𝗫𝗛𝗘 𝗣𝗔𝗜𝗗𝗔 𝗛𝗢 𝗝𝗔𝗔𝗬𝗘𝗡𝗚𝗘 🤣🔥",
    "𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗨𝗗𝗘𝗚𝗜 𝗕𝗘𝗧𝗘 𝗖𝗛𝗨𝗗 𝗝𝗔𝗬𝗘𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧 𝗙𝗔𝗧𝗘𝗚𝗜 𝗔𝗕💦💦🍆🍑😂",
    "𝗧𝗥𝗜𝗜 𝗕𝗔𝗔𝗔𝗣 𝗫𝗛𝗔𝗞𝗞𝗔 𝗛 𝗞𝗬𝗔 ??",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗢𝗗𝗞𝗘 𝗙𝗔𝗥𝗔𝗔𝗥 𝗛𝗢 𝗚𝗔𝗬𝗜😘😂😂😂",
    "𝗧𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗜𝗧𝗡𝗔 𝗫𝗛𝗢𝗗𝗨𝗡𝗚𝗔 𝗞𝗜 𝗫𝗛𝗨𝗧 𝗙𝗔𝗧 𝗝𝗔𝗔𝗬𝗘𝗚𝗜𝗜 🤤🤣🔥",
    "𝗔𝗣𝗡𝗜𝗜𝗜𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢𝗢 𝗣𝗔𝗜𝗗 𝗚𝗜𝗥𝗟𝗟𝗟 𝗕𝗡𝗔 𝗗𝗘𝗘𝗘𝗘 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗘 𝗚𝗨𝗕𝗕𝗔𝗥𝗘 𝗣𝗛𝗘𝗞 𝗞𝗘 𝗠𝗦𝗥𝗨𝗡𝗚𝗔 𝗧𝗨𝗝𝗛𝗘😂🤤💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗔𝗜 𝗦𝗔𝗥𝗜𝗬𝗔𝗟 𝗗𝗔𝗔𝗟 𝗞𝗘 𝗖𝗛𝗨𝗧 𝗦𝗘 𝗕𝗔𝗛𝗔𝗥 𝗡𝗜𝗞𝗔𝗟𝗨𝗡𝗚𝗔 💦🍆🍑😈",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗚𝗕 𝗥𝗢𝗔𝗗 𝗞𝗜 𝗦𝗔𝗦𝗧𝗜 𝗥𝗔𝗡𝗗𝗜 𝗛𝗔𝗜 𝗕𝗘𝗧𝗘😂💋🍑🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗕𝗣 𝗦𝗛𝗢𝗢𝗧 𝗞𝗔𝗥𝗞𝗘 𝗣𝗢𝗥𝗡𝗛𝗨𝗕 𝗣𝗘 𝗗𝗔𝗟𝗨𝗡𝗚𝗔 😝🍑😂🔥",
    "𝗔𝗔𝗝 𝗧𝗘𝗥𝗔 𝗞𝗛𝗔𝗡𝗗𝗔𝗡 𝗫𝗛𝗨𝗗𝗘𝗚𝗔 💦🍆🍑",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗣𝗘 𝗝𝗛𝗨𝗟𝗘𝗚𝗜🍆🍑😁",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗞𝗢 𝗗𝗔𝗗𝗗𝗬 𝗕𝗢𝗟𝗧𝗜 𝗛𝗔𝗜😂🤤🍑💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔 𝗚𝗔𝗡𝗚 𝗕𝗔𝗡𝗚 𝗞𝗥𝗔 𝗗𝗨𝗡𝗚𝗔 🤣🔥💋 ",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗨𝗦𝗜 𝗞𝗜 𝗫𝗛𝗨𝗧 𝗞𝗔𝗔𝗟𝗜 𝗔𝗬𝗘 𝗛𝗔𝗜 𝗧𝗘𝗥𝗜 𝗧𝗢𝗛 𝗛𝗨𝗠𝗡𝗘 𝗚𝗔𝗔𝗡𝗗 𝗙𝗔𝗔𝗗 𝗗𝗔𝗔𝗟𝗜💦🍆🍑🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗖𝗔𝗥 𝗟𝗔𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 𝗞𝗜𝗗𝗗 🤣🔥",
    "𝗧𝗘𝗥𝗔 𝗕𝗔𝗔𝗣 𝗞𝗢 𝗠𝗔𝗔𝗔𝗥 𝗗𝗨𝗡𝗚𝗔𝗔𝗔𝗔 𝗕𝗔𝗫𝗫𝗛𝗘 🤣👅 ",
    "𝗧𝗘𝗥𝗜 𝗚𝗔𝗔𝗡𝗗 𝗙𝗧 𝗟𝗘 𝗧𝗨𝗞𝗗𝗘 𝗛𝗢 𝗚𝗔𝗬𝗘 𝗖𝗛𝗔𝗔𝗥 𝗔𝗕𝗘 𝗖𝗛𝗔𝗟 𝗡𝗜𝗞𝗔𝗟 𝗪𝗔𝗥𝗡𝗔 𝗜𝗧𝗡𝗔 𝗠𝗔𝗥𝗨𝗡𝗚𝗔 𝗞𝗜 𝗛𝗢 𝗝𝗔𝗜𝗘𝗚𝗔 𝗧𝗘𝗥𝗔 𝗛𝗔𝗔𝗟 𝗕𝗘𝗛𝗔𝗟😂😎😈⚡️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔𝗔𝗔 𝗠𝗘𝗥𝗞𝗢 𝗗𝗔𝗗𝗗𝗬 𝗡𝗔𝗔𝗠 𝗦𝗘 𝗣𝗨𝗞𝗔𝗥𝗘𝗘𝗘😌😂😈🍑",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗦𝗕𝗦𝗘 𝗔𝗖𝗖𝗛𝗜 𝗣𝗔𝗜𝗗 𝗚𝗜𝗥𝗟 🤤💋",
    "𝗔𝗕𝗘 𝗔𝗔𝗝 𝗧𝗘𝗥𝗜 𝗚𝗔𝗔𝗡𝗗𝗔𝗜 𝗟𝗘𝗗 𝗙𝗜𝗧 𝗞𝗔𝗥𝗨𝗡𝗚𝗔 𝗙𝗜𝗥 𝗧𝗘𝗥𝗜 𝗧𝗔𝗔𝗡𝗗 𝗖𝗛𝗔𝗠𝗔𝗞 𝗨𝗧𝗛𝗘𝗚𝗜😂🍆🍑",
    "𝗧𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗦𝗔𝗦𝗧𝗔 𝗦𝗣𝗔𝗠🤣 𝗕𝗢𝗧 𝗟𝗔𝗚𝗔 𝗞𝗘 𝗦𝗣𝗔𝗠 𝗞𝗥𝗨𝗡𝗚𝗔 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗔𝗨𝗗𝗘 𝗣𝗘 𝗙𝗜𝗦𝗔𝗟 𝗞𝗔𝗥 𝗚𝗜𝗥 𝗚𝗔𝗬𝗜 𝗔𝗨𝗥 𝗣𝗥𝗘𝗚𝗡𝗔𝗡𝗧 𝗛𝗢 𝗚𝗔𝗬𝗜😂🍑🍆💋",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗡𝗘 𝗠𝗘𝗥𝗔 𝗡𝗨𝗠𝗕𝗘𝗥 𝗗𝗔𝗗𝗗𝗬 𝗡𝗔𝗠𝗘 𝗦𝗘 𝗦𝗔𝗩𝗘 𝗞𝗔𝗥 𝗥𝗞𝗛𝗔 𝗛𝗔𝗜🙈👻😈💋",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗢 𝗟𝗔𝗨𝗗𝗘 𝗣𝗘 𝗡𝗔𝗖𝗛𝗔𝗨𝗡𝗚𝗔 😂🍆🍑",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗗𝗜𝗘 𝗛𝗔𝗥𝗗 𝗙𝗔𝗡 𝗛𝗔𝗜 👻🙈😂💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗦𝗘 𝗣𝗘𝗛𝗟𝗘 3 𝗗𝗜𝗟𝗗𝗢 𝗔𝗨𝗥 𝗘𝗞 𝗩𝗜𝗕𝗥𝗔𝗧𝗢𝗥 𝗨𝗦𝗘 𝗞𝗔𝗥𝗧𝗜 𝗧𝗛𝗜😂🍑👻🍆💦",
    "𝗔𝗣𝗡𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗫𝗛𝗨𝗧 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗭𝗢𝗠𝗔𝗧𝗢 𝗠𝗔𝗜 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔 💋🤤🥵",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗔 𝗣𝗔𝗣𝗔 𝗞𝗔 𝗟𝗨𝗡𝗗 𝗠𝗔𝗜 𝗗𝗨𝗠 𝗡𝗔𝗛𝗜 𝗧𝗛𝗔 𝗜𝗦𝗟𝗜𝗬𝗘 𝗠𝗘𝗥𝗘 𝗦𝗘 𝗖𝗛𝗨𝗗𝗞𝗘 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗡𝗘 𝗧𝗨𝗝𝗛𝗘 𝗝𝗔𝗡𝗔𝗠 𝗗𝗜𝗬𝗔🍆💦🍑😂👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗔𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗔𝗠𝗔𝗭𝗢𝗡 𝗠𝗔𝗜 𝗦𝗘𝗟𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 50 𝗠𝗔𝗜 🤤💋😊❤️",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗢 𝗖𝗛𝗢𝗖𝗢𝗟𝗔𝗧𝗘 𝗙𝗟𝗔𝗩𝗢𝗨𝗥 𝗣𝗔𝗦𝗔𝗡𝗗 𝗛𝗔𝗜👻🍆🍑😂",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗘 𝗚𝗛𝗔𝗥 𝗞𝗘 𝗣𝗔𝗔𝗦 𝗪𝗔𝗟𝗘 𝗗𝗨𝗞𝗔𝗡 𝗠𝗔𝗜 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 200 𝗞𝗘 𝗕𝗛𝗔𝗩 𝗕𝗜𝗞 𝗥𝗛𝗜 𝗛𝗔𝗜😂👻🍆🍑",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗫𝗛𝗨𝗧 𝗦𝗕𝗦𝗘 𝗦𝗘𝗫𝗫𝗬 𝗛 𝗠𝗔𝗗𝗔𝗥𝗫𝗝𝗢𝗗 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗖𝗛𝗨𝗧 𝗙𝗔𝗧 𝗞𝗘 𝗛𝗢 𝗚𝗔𝗬𝗘 𝗧𝗨𝗞𝗗𝗘 𝗖𝗛𝗔𝗔𝗥😂🍑🍆👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧𝗧𝗧 𝗙𝗔𝗔𝗔𝗗 𝗞𝗘 𝗦𝗔𝗕 𝗦𝗘 𝗖𝗛𝗨𝗗𝗪𝗔𝗡𝗨𝗡𝗚𝗔 🤤💋🔥",
    "𝗔𝗡𝗗𝗜 𝗠𝗔𝗡𝗗𝗜 𝗦𝗔𝗡𝗗𝗜 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗫𝗛𝗨𝗧𝗧𝗧😂👻🍆🍑",
    "𝗔𝗔𝗨𝗞𝗔𝗔𝗧 𝗠𝗔𝗜 𝗥𝗘𝗛 𝗞𝗔𝗥 𝗕𝗔𝗔𝗧 𝗞𝗥 𝗟𝗜𝗬𝗔 𝗞𝗥 𝗕𝗔𝗫𝗫𝗛𝗘 𝗪𝗔𝗥𝗡𝗔 𝗠𝗔𝗔𝗔 𝗫𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 🤣🔥🖕",
    "𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗗𝗘𝗞𝗛𝗞𝗥 𝗗𝗔𝗘 𝗚𝗔𝗬𝗜 𝗗𝗔𝗥𝗞𝗘 𝗨𝗦𝗡𝗘 𝗗𝗜𝗬𝗔 𝗠𝗨𝗧 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗔𝗟𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧😂🍑👻",
    "𝗛𝗔𝗥𝗘 𝗛𝗔𝗥𝗘 𝗝𝗛𝗔𝗗𝗜𝗬𝗢 𝗠𝗘 𝗕𝗔𝗗𝗔 𝗕𝗔𝗗𝗔 𝗚𝗛𝗢𝗦𝗟𝗔 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂🍑🍆👻",
    "𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗠𝗘𝗥𝗔 𝗟𝗨𝗡𝗗 𝗗𝗘𝗞𝗛𝗞𝗥 𝗗𝗔𝗘 𝗚𝗔𝗬𝗜 𝗗𝗔𝗥𝗞𝗘 𝗨𝗦𝗡𝗘 𝗗𝗜𝗬𝗔 𝗠𝗨𝗧 𝗔𝗥𝗘 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗞𝗔𝗔𝗟𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧𝗧𝗧𝗧𝗧😂🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗟𝗘𝗞𝗘 𝗕𝗛𝗔𝗚 𝗝𝗔𝗔𝗨𝗡𝗚𝗔  🤤💋𝗔𝗨𝗥 𝗞𝗔𝗟 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔  𝗗𝗜𝗞𝗛𝗘𝗚𝗜 𝗖𝗜𝗗 𝗠𝗔𝗜 🤣🔥",
    "𝗔𝗥𝗘 𝗕𝗘𝗧𝗘 𝗬𝗔𝗦𝗛 𝗔𝗨𝗥 𝗟𝗨𝗖𝗜𝗙𝗘𝗥 𝗞𝗘 𝗣𝗜𝗥𝗢 𝗕𝗢𝗧 𝗦𝗘 𝗖𝗛𝗨𝗗 𝗚𝗔𝗬𝗔 𝗧𝗨 𝗡𝗜𝗞𝗟 𝗪𝗔𝗥𝗡𝗔 𝗔𝗨𝗥 𝗖𝗛𝗨𝗗𝗘𝗚𝗔 𝗕𝗘𝗧𝗘😁🍆🔥🍑",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗞𝗜 𝗞𝗔𝗔𝗟𝗜 𝗫𝗛𝗨𝗧 𝗟𝗘𝗔𝗞 𝗞𝗔𝗥 𝗥𝗛𝗜 𝗛𝗔𝗜 𝗠𝗔𝗜 𝗣𝗟𝗨𝗠𝗕𝗘𝗥 𝗛𝗨 𝗥𝗨𝗞 𝗧𝗛𝗜𝗞 𝗞𝗔𝗥 𝗗𝗨𝗡𝗚𝗔😂🍆🍑👻",
    "𝗔𝗡𝗗𝗜𝗜 𝗠𝗔𝗡𝗗𝗜𝗜𝗜 𝗦𝗛𝗔𝗡𝗗𝗜𝗜𝗜 𝗔𝗚𝗔𝗥 𝗗𝗨𝗦𝗠𝗔𝗡 𝗟𝗢𝗚 𝗥𝗘𝗣𝗟𝗬 𝗞𝗜𝗬𝗔 𝗧𝗢𝗛 𝗨𝗦𝗞𝗔 𝗠𝗔 𝗕𝗛𝗘𝗡 𝗥𝗔𝗡𝗗𝗜𝗜 😅😅😒",
    "𝗧𝗨 𝗔𝗨𝗥 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗖𝗔𝗥 𝗖𝗛𝗔𝗗𝗔 𝗗𝗨𝗡𝗚𝗔 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 🤣🔥",
    "𝗔𝗥𝗘 𝗝𝗬𝗔𝗗𝗔 𝗨𝗗 𝗠𝗔𝗧 𝗪𝗔𝗥𝗡𝗔 𝗣𝗛𝗢𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗔 𝗞𝗛𝗢𝗣𝗗𝗔 𝗔𝗨𝗥 𝗝𝗬𝗔𝗗𝗔 𝗕𝗢𝗟𝗘𝗚𝗔 𝗧𝗢𝗛 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗔 𝗕𝗚𝗢𝗦𝗗𝗔😂🍆🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗦𝗔𝗕 𝗞𝗢 𝗕𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣✌️",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔𝗔 𝗞𝗢 𝗞𝗜𝗗𝗡𝗔𝗣 𝗞𝗥𝗞𝗘 𝗡𝗔𝗡𝗚𝗔 𝗥𝗢𝗔𝗗 𝗣𝗘 𝗫𝗛𝗢𝗗 𝗗𝗨𝗡𝗙𝗔 🤣🤤🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗬𝗬𝗜𝗔 𝗧𝗢𝗛 𝗞𝗔𝗟𝗔𝗣𝗡𝗘 𝗟𝗔𝗚𝗜 🤣🥺",
    "𝗔𝗕𝗘 𝗞𝗜𝗗 𝗕𝗛𝗢𝗞 𝗠𝗔𝗧 𝗝𝗬𝗔𝗗𝗔 𝗪𝗔𝗥𝗡𝗔 𝗔𝗡𝗗𝗔𝗥 𝗦𝗘 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗞𝗛𝗢𝗞𝗟𝗔 𝗔𝗨𝗥 𝗔𝗕 𝗞𝗨𝗖𝗛 𝗕𝗢𝗟𝗔 𝗧𝗢𝗛 𝗙𝗔𝗔𝗗 𝗗𝗨𝗡𝗚𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂🍆🍑😜👻",
    "𝗧𝗘𝗥𝗜𝗜 𝗠𝗔 𝗠𝗘𝗥𝗘 𝗞𝗔𝗕𝗝𝗘 𝗠𝗔𝗜 𝗛𝗔𝗜 𝗟𝗘𝗡𝗔 𝗠𝗔𝗡 𝗛𝗔𝗜 𝗧𝗢𝗛 𝗣𝗔𝗬 10000000 🤣🤣🤣",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗠𝗢𝗔𝗡 𝗣𝗘 𝗕𝗛𝗜 𝗛𝗜𝗟𝗔 𝗟𝗘𝗧𝗔 𝗛𝗨 𝗜𝗧𝗡𝗜 𝗛𝗢𝗧 𝗛𝗔𝗜 𝗩𝗢𝗛🙈😂👻🍆",
    "𝗧𝗘𝗥𝗜 𝗕𝗘𝗛𝗘𝗡 𝗞𝗜𝗧𝗡𝗜 𝗛𝗢𝗧 𝗛𝗔𝗜 𝗬𝗔𝗔𝗥 𝗠𝗔𝗡 𝗞𝗥𝗧𝗔 𝗛𝗔𝗜 𝗜𝗧𝗡𝗔 𝗖𝗛𝗢𝗗𝗨 𝗞𝗜 𝗔𝗨𝗥 𝗞𝗢𝗜 𝗖𝗛𝗢𝗗 𝗡𝗔 𝗣𝗔𝗬𝗘 𝗨𝗦𝗞𝗢😂🍑🍆👻",
    "𝗧𝗔𝗔𝗥𝗔𝗞 𝗠𝗘𝗛𝗧𝗔 𝗞𝗔 𝗨𝗟𝗧𝗔 𝗖𝗛𝗔𝗦𝗠𝗔 𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗔 𝗕𝗔𝗗𝗔 𝗕𝗔𝗗𝗔 𝗕𝗛𝗢𝗦𝗗𝗔😂👻🍑🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗣𝗧𝗔𝗞 𝗞𝗘 𝗫𝗛𝗢𝗗 𝗗𝗘𝗡𝗚𝗘 𝗞𝗜 𝗣𝗔𝗧𝗔 𝗩 𝗡𝗛𝗜 𝗖𝗛𝗔𝗟𝗘𝗚𝗔 𝗔𝗨𝗥 𝗕𝗔𝗫𝗫𝗛𝗔 𝗣𝗔𝗜𝗗𝗔 𝗞𝗥 𝗗𝗘𝗚𝗜 🤣🤤🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗢𝗬𝗢 𝗟𝗘 𝗝𝗔𝗔𝗞𝗥 𝗣𝗘𝗟𝗨𝗡𝗚𝗔 𝗜𝗧𝗡𝗔 𝗞𝗜 𝗞𝗔𝗕𝗛𝗜 𝗖𝗛𝗨𝗧 𝗡𝗔𝗛𝗜 𝗗𝗜𝗞𝗛𝗔 𝗣𝗔𝗬𝗘𝗚𝗜 𝗙𝗜𝗥😂🍆👻🍑💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗔𝗜 𝗜𝗡𝗦𝗧𝗔𝗚𝗥𝗔𝗠 𝗞𝗔 𝗥𝗘𝗘𝗟 𝗟𝗚𝗔 𝗗𝗨𝗡𝗚𝗔 🤤🙈💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗧𝗜𝗞𝗧𝗢𝗞 𝗞𝗜 𝗦𝗔𝗦𝗧𝗜 𝗥𝗔𝗡𝗗𝗜 𝗛𝗔𝗜😂🍆💋",
    "𝗧𝗘𝗥𝗜 𝗕𝗛𝗘𝗡 𝗞𝗔 𝗕𝗛𝗢𝗦𝗔𝗗𝗔 𝗙𝗔𝗔𝗗 𝗞𝗘 𝗔𝗠𝗔𝗭𝗢𝗡 𝗠𝗔𝗜 𝗦𝗘𝗟𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 1 𝗠𝗔𝗜 🥺🤣💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗗𝗨𝗕𝗔𝗜 𝗠𝗔𝗜 𝗕𝗛𝗘𝗝 𝗗𝗨𝗡𝗚𝗔 𝗔𝗨𝗥 𝗫𝗛𝗨𝗗𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗨𝗦𝗞𝗔 𝗣𝗥𝗜𝗡𝗖𝗘 𝗦𝗘 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗣𝗥𝗜𝗩𝗔𝗧𝗘 𝗩𝗜𝗟𝗟𝗔 𝗟𝗘 𝗝𝗔𝗔𝗞𝗥 𝗣𝗘𝗟𝗨𝗡𝗚𝗔 😂🍆💋🍑",
    "𝗜 𝗙𝗨𝗖𝗞𝗘𝗗 𝗨𝗥 𝗠𝗢𝗠 😂🍆",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗪𝗜𝗟𝗟 𝗦𝗨𝗖𝗞 𝗠𝗬 𝗗𝗜𝗖𝗞😂🍆🍑",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗔𝗡𝗗 𝗦𝗜𝗦𝗧𝗘𝗥 𝗜𝗦 𝗩𝗘𝗥𝗬 𝗛𝗢𝗧𝗧 𝗠𝗔𝗡 𝗦𝗛𝗘 𝗦𝗨𝗖𝗞'𝗦 𝗠𝗬 𝗗𝗜𝗖𝗞 𝗘𝗩𝗘𝗥𝗬𝗗𝗔𝗬🙈🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗫𝗫 𝗩𝗜𝗥𝗔𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗕𝗔𝗫𝗖𝗛𝗘 🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗨𝗗𝗞𝗘 𝗗𝗔𝗥 𝗚𝗔𝗬𝗜 𝗬𝗔𝗔𝗥💦👻🙈",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗔 𝗠𝗜𝗗𝗗𝗟𝗘 𝗙𝗜𝗡𝗚𝗘𝗥 𝗡𝗔𝗜𝗟 𝗡𝗔𝗛𝗜 𝗛𝗔𝗜😂👻🍑🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔 𝗫𝗛𝗨𝗗𝗔𝗜 𝗔𝗟𝗜𝗩𝗘 𝗣𝗜𝗖 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 🤤😂",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗖𝗛𝗢𝗗𝗧𝗘 𝗪𝗔𝗞𝗧 𝗬𝗢𝗨𝗧𝗨𝗕𝗘 𝗣𝗘 𝗟𝗜𝗩𝗘 𝗞𝗔𝗥𝗨𝗡𝗚𝗔😂🍆🍑💦",
    "𝗔𝗕𝗜 𝗩 𝗧𝗜𝗠𝗘 𝗛 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗣𝗔𝗣𝗔 𝗕𝗢𝗟 𝗔𝗨𝗥 𝗟𝗨𝗡𝗗 𝗣𝗞𝗔𝗗 🤣🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘 𝗫𝗛𝗨𝗧  𝗠𝗔𝗜 𝗥𝗢𝗖𝗞𝗘𝗧 𝗟𝗔𝗨𝗡𝗖𝗛 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗡𝗔𝗦𝗔 𝗪𝗔𝗟𝗔 🤤💋😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗔𝗥𝗔𝗠 𝗚𝗔𝗥𝗔𝗠 𝗧𝗘𝗟 🥺🤣💋",
    "𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗔𝗔𝗚𝗬𝗘 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗞𝗔𝗟𝗔𝗣 𝗠𝗧 𝗔𝗕 🤣🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗘𝗞 𝗔𝗨𝗥 𝗫𝗛𝗨𝗧 𝗗𝗔𝗟𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗥𝗡𝗗𝗜 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗣𝗘 𝗖𝗥𝗜𝗖𝗞𝗘𝗧 𝗞𝗛𝗘𝗟𝗡𝗚𝗘 🤣😱",
    "𝗨𝗙𝗙 𝗖𝗛𝗨𝗗 𝗚𝗔𝗬𝗔 𝗕𝗘𝗧𝗔 𝗔𝗕 𝗕𝗛𝗢𝗞 𝗖𝗛𝗨𝗧𝗜𝗬𝗔 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗟𝗔𝗗𝗡𝗘 𝗔𝗔𝗬𝗔 𝗧𝗛𝗔 𝗡𝗔😂🍆🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗣𝗨𝗦𝗦𝗬 𝗖𝗛𝗔𝗧𝗨𝗡𝗚𝗔 𝗕𝗘𝗧𝗘😂🍑🍆🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗥𝗔𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗞𝗜 𝗠𝗔𝗡𝗔𝗚𝗘𝗥 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗞𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗟𝗢 𝗣𝗔𝗥 𝗣𝗔𝗜𝗦𝗘 𝗗𝗘𝗧𝗘 𝗝𝗔𝗔𝗡𝗔 🤣🔥🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗙𝗔𝗡 𝗛𝗔𝗜😍👻💋🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗞𝗘 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔𝗔𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣🔥",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗕 𝗣𝗔𝗣𝗔 𝗚𝗔𝗟𝗧𝗜 𝗛𝗢 𝗚𝗔𝗬𝗜 𝗠𝗔𝗔𝗙 𝗞𝗔𝗥𝗗𝗢😁🍑🍆👻",
    "𝗔𝗣𝗡𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗚𝗔𝗔𝗔𝗡𝗗 𝗗𝗘𝗗𝗢 🥺 𝗧𝗛𝗢𝗗𝗜 𝗗𝗘𝗥 𝗣𝗘𝗟 𝗞𝗘 𝗗𝗘𝗧𝗔 𝗛𝗨 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗛𝗔𝗥 𝗕𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 𝗟𝗢𝗗𝗘 🤤💋",
]


RRAID = [
    "MADARXHODD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
]
